sonar.projectKey=clarivex-tech_pervaxis-canvas
sonar.organization=clarivex-tech
sonar.projectName=Pervaxis Canvas
sonar.host.url=https://sonarcloud.io

sonar.sources=libs,apps
sonar.tests=libs,apps
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.nx/**,**/*.spec.ts,**/coverage/**,**/*.stories.ts,**/e2e/**
sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/.nx/**,**/*.stories.ts,**/e2e/**,apps/**

# Vitest c8 produces lcov.info under coverage/libs/<category>/<name>/lcov.info
sonar.javascript.lcov.reportPaths=coverage/libs/shell/core/lcov.info,\
  coverage/libs/shell/auth/lcov.info,\
  coverage/libs/shell/routing/lcov.info,\
  coverage/libs/shell/layout/lcov.info,\
  coverage/libs/platform/http/lcov.info,\
  coverage/libs/platform/auth/lcov.info,\
  coverage/libs/platform/state/lcov.info,\
  coverage/libs/platform/error/lcov.info,\
  coverage/libs/platform/i18n/lcov.info,\
  coverage/libs/mfe/contracts/lcov.info,\
  coverage/libs/mfe/bootstrap/lcov.info,\
  coverage/libs/mfe/testing/lcov.info,\
  coverage/libs/components/web/lcov.info,\
  coverage/libs/components/mobile/lcov.info

sonar.typescript.tsconfigPaths=tsconfig.base.json
sonar.qualitygate.wait=true
